apiVersion: v1
kind: Service
metadata:
  name: {{ template "toxiproxy.fullname" . }}
  labels:
    app: {{ template "resiproxy.name" . }}
    chart: {{ .Chart.Name }}-{{ .Chart.Version | replace "+" "_" }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.toxiproxy.type }}
  ports:
    - port: {{ .Values.service.toxiproxy.externalPort }}
      targetPort: {{ .Values.service.toxiproxy.internalPort }}
      protocol: TCP
      name: http-{{ .Values.service.toxiproxy.name }}
  selector:
    app: {{ template "resiproxy.name" . }}
    release: {{ .Release.Name }}
