{{ if not .Values.ingress.internal }}
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: dbk-psa-{{ .Values.name }}-cert
spec:
  # Secret names are always required.
  secretName: {{ .Values.name }}-{{ .Values.ingress.tlsSecretSuffix }}
  duration: 2160h0m0s # 90d
  renewBefore: 360h0m0s # 15d
  subject:
    organizations:
    - ncr-dbk-{{ .Values.name }}
  # The use of the common name field has been deprecated since 2000 and is
  # discouraged from being used.
  commonName: {{ template "ingress.host" . }}
  privateKey:
    algorithm: RSA
    encoding: PKCS1
    size: 2048
  usages:
    - server auth
    - client auth
  # At least one of a DNS Name, URI, or IP address is required.
  dnsNames:
  - {{ template "ingress.host" . }}
  issuerRef:
    name: {{ .Values.ingress.cert.issuer }}
    kind: ClusterIssuer
    # This is optional since cert-manager will default to this value however
    # if you are using an external issuer, change this to that issuer group.
    group: cert-manager.io
{{- end }}