apiVersion: v1
kind: Service
metadata:
  name: "dbk-psa-{{ .Values.name }}-svc"
spec:
  type: "{{ .Values.service.type }}"
  ports:
    - port: 8080
      targetPort: http
      protocol: TCP
      name: http
    {{- if hasKey .Values "pte" }}
    - protocol: TCP
      name: jolokia
      port: {{ .Values.pte.jolokiaPort }}
      targetPort: {{ .Values.pte.jolokiaPort }}
    {{- end }}
  selector:
    app: "{{ .Values.name }}"
